### ISSUE TITLE
Error on detection of integer objetive value

### ISSUE THREAD

**Issue by euchoa** [inria-UFF/BaPCodVRPSolver.jl#1]
CVRP run julia src/run.jl data/tai/tai75a.vrp --noround -u 1619 misses the optimal solution of 1618.36

Dual bounds are being rounded up 
1616.3 (rounded: 1617)

even if the costs are fractional.

**Comment by rrsadykov** [comment]
@EduardoQueiroga 
Can you please look at this issue?

**Comment by EduardoQueiroga** [comment]
I think Julia's interface passes the correct flag to the C++ side. In bapcod/wrapper/model.jl, we have:
function new!(param_file::String, print_param::Bool, **int_obj**::Bool, int_valued_bound::Bool, argc::Cint, argv::Array{String})
    @bcm_ccall("new", Ptr{Cvoid}, (Ptr{UInt8}, UInt8, UInt8, UInt8, Cint, Ptr{Ptr{UInt8}}),
                                param_file, print_param, **int_obj**, int_valued_bound, argc, argv)
end 

I did some prints there to confirm that it has been corrected passed (false in the example). 

It is received by (bcCinterfaceModel.cpp):
InterfaceModel::InterfaceModel(char* paramFile, bool printParam, **bool intObj**, bool intBound, int argc, char** argv) :
        problemInit(false),
        decompositionUsed(false),
        init(argc, argv, paramFile, printParam, true),
        **model(init, "BaPCodModel", (intObj) ? BcObjStatus::minInt : BcObjStatus::minFloat),**
        objective(model),
        mpform(model),
        master(model),
        colGenSp(model),
        solution(NULL),
        initialSolution(NULL),
        lastInitialSolution(NULL)
{

We should investigate further.

**Comment by rrsadykov** [comment]
Dear @EduardoQueiroga , 
I have updated BaPCod library to version 0.72.2 trying to solve this issue. Can you please try again to see if it works?

**Comment by EduardoQueiroga** [comment]
Dear @rrsadykov 

I think now it is working:

```
VRPSolver v0.5.21, 4/10/2022, © Inria Bordeaux, France, vrpsolver.math.u-bordeaux.fr
Corresponds to the solver by Pessoa, Sadykov, Uchoa and Vanderbeck (2020)
Paper: dx.doi.org/10.1007/s10107-020-01523-z
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   BaPCod v0.72.2, 19/10/2022, © Inria Bordeaux, France, bapcod.math.u-bordeaux.fr 
           USE THIS CODE ONLY FOR ACADEMIC PURPOSES AT YOUR OWN RISK
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
Reduced cost fixing for graph G_1...  took 0.04 sec., done by inspection with 89677 solutions, remains 46439 (51.8%)
ColGenEvalAlg final dual bound: **945.532 (rounded: 945.532)**
...
************************************************************************************************
BaPCod : solution defined.
statistics_cols: instance & :Optimal & cutoff & :bcRecRootDb & :bcTimeRootEval & :bcCountNodeProc & :bcRecBestDb & :bcRecBestInc & :bcTimeMain \\
statistics: R112 & 1 & 950.0 & 948.60 & 53.32 & 1 & 948.60 & 948.60 & 53.33 \\
```

I also tested for CVRP, and it is rounding up:
ColGenEvalAlg final dual bound: **27232.5 (rounded: 27233)**

Thank you.
